
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLiQuanCaPhe.Models
{

    using QuanLiQuanCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class ChiTietDonhang: BaseViewModel
    {

        private string _MADH;
    public string MADH { get=>_MADH; set {
                _MADH = value;OnPropertyChanged();
            } }

        private string _MAMON;
    public string MAMON { get=> _MAMON; set {
                _MAMON = value;OnPropertyChanged();
            } }

        private Nullable<double> _SOLUONG;
    public Nullable<double> SOLUONG { get=> _SOLUONG; set {
                _SOLUONG = value;OnPropertyChanged();
            } }

        private Nullable<double> _DONGIA;
    public Nullable<double> DONGIA { get=> _DONGIA; set { 
                _DONGIA = value; OnPropertyChanged(); 
            } }

        private Nullable<double> _THANHTIEN;
    public Nullable<double> THANHTIEN { get=> _THANHTIEN; set {
                _THANHTIEN = value;OnPropertyChanged();
            } }

        private Nullable<double> _GIAMGIA;
    public Nullable<double> GIAMGIA { get=> _GIAMGIA; set {
                _GIAMGIA = value;OnPropertyChanged();
            } }

        private Nullable<int> _ISDEL;
    public Nullable<int> ISDEL { get=> _ISDEL; set {
                _ISDEL = value;OnPropertyChanged();
            } }

        private Nullable<System.DateTime> _CREADTEDAT;
    public Nullable<System.DateTime> CREADTEDAT { get=> _CREADTEDAT; set {
                _CREADTEDAT = value;OnPropertyChanged();
            } }

        private Nullable<System.DateTime> _UPDATEDAT;
    public Nullable<System.DateTime> UPDATEDAT { get=> _UPDATEDAT; set {
                _UPDATEDAT = value; OnPropertyChanged();
            } }



    public virtual DonHang DonHang { get; set; }

    public virtual MonAn MonAn { get; set; }

}

}
