
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLiQuanCaPhe.Models
{
    using QuanLiQuanCaPhe.ViewModel;
    using System;
    using System.Collections.Generic;
    
public partial class NhanVien:BaseViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhanVien()
    {

        this.DonHangs = new HashSet<DonHang>();

        this.LichLamViecs = new HashSet<LichLamViec>();

    }

    private string _MANV;
    public string MANV { get => _MANV; set
            { _MANV = value;OnPropertyChanged(); } }

        private string _HOTEN;
    public string HOTEN { get=>_HOTEN; set {
                _HOTEN = value;OnPropertyChanged();
            } }

        private Nullable<double> _LUONG;
    public Nullable<double> LUONG { get=>_LUONG; set {
                _LUONG = value;OnPropertyChanged();
            } }

        private Nullable<System.DateTime> _NGSINH;
    public Nullable<System.DateTime> NGSINH { get=>_NGSINH; set {
                _NGSINH = value;OnPropertyChanged();
            } }

        private string _PHAI;
    public string PHAI { get=>_PHAI; set {
                _PHAI = value;OnPropertyChanged();
            } }

        private string _CMND;
    public string CMND { get=>_CMND; set {
                _CMND = value;OnPropertyChanged();
            } }

        private string _DIACHI;
    public string DIACHI { get=>_DIACHI; set {
                _DIACHI = value;OnPropertyChanged();
            } }

        private string _DIENTHOAI;
    public string DIENTHOAI { get=>_DIENTHOAI; set {
                _DIENTHOAI = value;OnPropertyChanged();
            } }

        private string _CHUCVU;
    public string CHUCVU { get=>_CHUCVU; set {
                _CHUCVU = value;OnPropertyChanged();
            } }

        private byte[] _HINHANh;
    public byte[] HINHANh { get=>_HINHANh; set {
                _HINHANh = value;OnPropertyChanged();
            }
        }

        private string _TAIKHOAN;
    public string TAIKHOAN { get=>_TAIKHOAN; set {
                _TAIKHOAN = value; OnPropertyChanged();
            } }

        private string _MATKHAU;
    public string MATKHAU { get=>_MATKHAU; set {
                _MATKHAU = value; OnPropertyChanged();
            }
        }

        private Nullable<int> _ISDEL;
    public Nullable<int> ISDEL { get=>_ISDEL; set {
                _ISDEL = value;OnPropertyChanged();
            } }

        private Nullable<System.DateTime> _CREATEDAT;
    public Nullable<System.DateTime> CREADTEDAT { get=>_CREATEDAT; set {
                _CREATEDAT = value; OnPropertyChanged();
            } }

        private Nullable<System.DateTime> _UPDATEDAT;
    public Nullable<System.DateTime> UPDATEDAT { get=>_UPDATEDAT; set {
                _UPDATEDAT = value; OnPropertyChanged();
            } }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DonHang> DonHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LichLamViec> LichLamViecs { get; set; }

}

}
