//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiQuanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.LichLamViecs = new HashSet<LichLamViec>();
        }

		public NhanVien(string mANV, string hOTEN, double? lUONG, DateTime? nGSINH,
			string pHAI, string cMND, string dIACHI, string dIENTHOAI, string cHUCVU,
			string tAIKHOAN, string mATKHAU, int? iSDEL, DateTime? cREADTEDAT, 
			DateTime? uPDATEDAT)
		{
			MANV = mANV;
			HOTEN = hOTEN;
			LUONG = lUONG;
			NGSINH = nGSINH;
			PHAI = pHAI;
			CMND = cMND;
			DIACHI = dIACHI;
			DIENTHOAI = dIENTHOAI;
			CHUCVU = cHUCVU;
			TAIKHOAN = tAIKHOAN;
			MATKHAU = mATKHAU;
			ISDEL = iSDEL;
			CREADTEDAT = cREADTEDAT;
			UPDATEDAT = uPDATEDAT;
		}

		public string MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<double> LUONG { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string PHAI { get; set; }
        public string CMND { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string CHUCVU { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<int> ISDEL { get; set; }
        public Nullable<System.DateTime> CREADTEDAT { get; set; }
        public Nullable<System.DateTime> UPDATEDAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichLamViec> LichLamViecs { get; set; }

		public override bool Equals(object obj)
		{
			return obj is NhanVien vien &&
				   MANV == vien.MANV &&
				   HOTEN == vien.HOTEN &&
				   EqualityComparer<double?>.Default.Equals(LUONG, vien.LUONG) &&
				   EqualityComparer<DateTime?>.Default.Equals(NGSINH, vien.NGSINH) &&
				   PHAI == vien.PHAI &&
				   CMND == vien.CMND &&
				   DIACHI == vien.DIACHI &&
				   DIENTHOAI == vien.DIENTHOAI &&
				   CHUCVU == vien.CHUCVU &&
				   TAIKHOAN == vien.TAIKHOAN &&
				   MATKHAU == vien.MATKHAU &&
				   EqualityComparer<int?>.Default.Equals(ISDEL, vien.ISDEL) &&
				   EqualityComparer<DateTime?>.Default.Equals(CREADTEDAT, vien.CREADTEDAT) &&
				   EqualityComparer<DateTime?>.Default.Equals(UPDATEDAT, vien.UPDATEDAT);
		}
	}
}
